In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [3]:
!mkdir ~/.kaggle

In [8]:
!cp /content/drive/MyDrive/'Colab Notebooks'/kaggle.json ~/.kaggle/

In [10]:
!chmod 600 /content/drive/MyDrive/'Colab Notebooks'/kaggle.json
!kaggle datasets download carloscll/wild-rift-data-for-practive-fake-data

Dataset URL: https://www.kaggle.com/datasets/carloscll/wild-rift-data-for-practive-fake-data
License(s): apache-2.0
wild-rift-data-for-practive-fake-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [11]:
!unzip wild-rift-data-for-practive-fake-data.zip

Archive:  wild-rift-data-for-practive-fake-data.zip
  inflating: wild_rift_fake_data.csv

In [44]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [45]:
df = pd.read_csv('wild_rift_fake_data.csv')

In [46]:
df['herois'][28]

'Fiora'

In [47]:
df.drop(index=28, inplace=True)

In [48]:
df['herois']

0             Gwen
1             Ornn
2            Fiora
3             Nami
4          Caitlyn
5              Jax
6             Sett
7             Jhin
8           Camile
9          Warwick
10           Veiga
11            Jinx
12           Yasuo
13            Ahri
14           Garen
15       Seraphine
16           Vayne
17          Darius
18           Akali
19             Lux
20         Lee Sin
21            Ashe
22             Zed
23        Malphite
24        Katarina
25          Draven
26          Soraka
27           Amumu
29           Janna
30    Twisted Fate
31    Miss Fortune
32              Vi
33            Lulu
34           Nasus
35           Braum
36          Ezreal
37         Camille
38          Wukong
39            Sona
40          Kennen
Name: herois, dtype: object

In [49]:
df.head()

    Win_rate    DPS  Assistance  Kills   herois
0  41.443265   5323           9      7     Gwen
1  46.992508   2761          10     16     Ornn
2  54.822255  10812          15     11    Fiora
3  45.407249  12811          12     19     Nami
4  55.247829  16439          13      7  Caitlyn

In [50]:
hero_mapping = {hero: i for i, hero in enumerate(df['herois'].unique())}
df['herois'] = df['herois'].map(hero_mapping)
df['herois']

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
26    26
27    27
29    28
30    29
31    30
32    31
33    32
34    33
35    34
36    35
37    36
38    37
39    38
40    39
Name: herois, dtype: int64

In [51]:
df.head()

    Win_rate    DPS  Assistance  Kills  herois
0  41.443265   5323           9      7       0
1  46.992508   2761          10     16       1
2  54.822255  10812          15     11       2
3  45.407249  12811          12     19       3
4  55.247829  16439          13      7       4

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 0 to 40
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Win_rate    40 non-null     float64
 1   DPS         40 non-null     int64
 2   Assistance  40 non-null     int64
 3   Kills       40 non-null     int64
 4   herois      40 non-null     int64
dtypes: float64(1), int64(4)
memory usage: 1.9 KB

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('herois', axis=1), df['herois'], test_size=0.2, random_state=42)

In [56]:
from sklearn.linear_model import LinearRegression

In [58]:
model=LinearRegression()

In [59]:
model.fit(X_train, y_train)

LinearRegression()

In [60]:
predictions = model.predict(X_test)

In [64]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [65]:
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)

In [66]:
print(mse)
print(r2)
print(mae)

149.84711256692944
-0.6332110361518195
10.79858286911562

In [85]:
my_stats = pd.DataFrame({
    'Win_rate': [70.0],
    'DPS': [7000],
    'Assistance': [5],
    'Kills': [10]
})

reverse_hero_mapping = {v: k for k, v in hero_mapping.items()}

My_Champion = model.predict(my_stats)

My_Champion = int(My_Champion[0])

My_Champion_Name = reverse_hero_mapping[My_Champion]

print('The Champion you should pick is: ', My_Champion_Name)

The Champion you should pick is:  Malphite